/*
Ryan Cantone
ASDI 1401
Project Week 2
*/

var json = {
	"account1":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
	"account2":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account3":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account4":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account5":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account6":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account7":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account8":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account9":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account10":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account11":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account12":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account13":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account14":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account15":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account16":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account17":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account18":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account19":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
		"account20":{
		"alias": ["Account:", "Facebook"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Cantone"],
		"eMail": ["Email:", "ryan.cantone@fullsail.edu"],
		"bDay": ["Birth Date:", "12-12-1987"],
		"language": ["Language:", "English"],
		"skill": ["Socialable:", "8"],
		"sex": ["Sex:", "Male"],
		"pro": ["Profession:", "Student"],
		"division": ["Location:", "East"],
		"notes": ["Notes:", "This is my main account."],
	},
	
}